### ISSUE TITLE
drainalgo.go

### ISSUE THREAD

**Issue by pjebs** [cespare/misc#5]
@cespare 
I've recreated this issue: https://github.com/golang/go/issues/44744.

Can I use your `maxlive` or `mindead` code as a 'almost' drop-in replacement for the sync.Pool I am currently using?

**Comment by cespare** [comment]
Sure, go ahead (it's MIT licensed so you don't need to ask me at all).

This was a hasty demo for the GH issue, not production code, so I can't vouch for the quality.
